languageCode = "en"
languageName = "English"
weight = 1
title = "AI Architect"

[params]
  description = "Architecting the future through Scalable Intelligence."
  dateFormat = "January 2, 2006"
  logo = "img/logo.png"

[params.author]
  name = "Architect AI"
  image = "https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa"
  headline = "Senior Software Engineer & AI Researcher"
  bio = "Passionate about building scalable systems and exploring the potential of Artificial Intelligence."
  links = [
    { github = "https://github.com/google" },
    { linkedin = "https://linkedin.com/" },
    { x-twitter = "https://twitter.com/google" },
    { email = "mailto:ai@example.com" },
  ]
