[goldmark]
  [markup.goldmark.renderer]
    unsafe = true # Required for many shortcodes and Mermaid

[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNoNumbers = true
  style = "monokai"

[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
