# -- Theme Options --
colorScheme = "terminal" # Cool professional look
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # Professional profile look
  showRecent = true
  cardView = true

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  sharingLinks = ["linkedin", "twitter", "reddit", "email"]
