baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Blowfish AI Project'
theme = "blowfish"

# Blowfish specific configurations
[params]
  colorScheme = "blowfish" # options: blowfish, fire, horizon, lime, ocean, pink, purple, sky, sunset, terminal, woods
  defaultAppearance = "dark" # options: light, dark, switcher
  showArticleCard = true
  showRecent = true
  showBreadcrumbs = true
  showBackToTop = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"
    title = "Blowfish AI Project"

  [languages.fr]
    languageName = "Fran√ßais"
    weight = 2
    contentDir = "content"
    title = "Projet AI Blowfish"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 10

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 20
